version: '3'

services:
  backend-spendless:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_spendless
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

volumes:
    backend-spendless: